### ISSUE TITLE
CrossPlan simplification problems 

### ISSUE THREAD

**Issue by LStrachan** [HighlanderLab/SIMplyBee#507]
Last decided was to get rid of the drone IDs and stick only to drone colony IDs which can only create(). 
- What happens with real data where the colonies drones come from are unknown? 

Currently there is a rule that only mated colonies produce drones.
-  Option to get rid of this rule in droneColonies since no genetic information comes from the father so virgin colonies would be enough (though this isn't biologically accurate). 

 Another option is to keep mating to the drones in the cross plan, creating a DCA from founderQueens MapPop and using dronePackages made from DCA to mate with VirginColonies
       - Problem with this is when the number of virginColonies gets too large and the numbers of dronePackages would be huge 
  
Possibility to ignore the mated virgin queen rule but only in the initial set up from the founderQueens?

**Comment by LStrachan** [comment]
![img_3127_720](https://user-images.githubusercontent.com/80959752/230389118-7f87d926-ed56-4dd7-970b-625b4c500924.jpg)

Notes taken from the last meeting

**Comment by JerBub** [comment]
we can create function for setting up founder colonies. This function should allow crating drones from virgin queens. In neext step we would have colonies with virgin queens and drones. Now, we can cross colony to colony.

**Comment by janaobsteter** [comment]
OK, summarising the options again:

- keep the option to mate with drones specifically in the cross plan --> downside: this is complicated since we have about 10 different options to mate a queen
- only allow mating with colonies in the cross plan --> downside: this means that initial drone colonies must be mated to drone packages (and not via cross plan) which could be computationally demanding & what happens when people have real pedigrees and want to mate to specific drones
- get rid of the rule that only mated colonies can produce drones --> can this bit us in the ass later on?
- create a function "createInitialMatedColonies" in which the rule of not creating drones from the virgin colonies could be breached

**Comment by janaobsteter** [comment]
Also, when the cross was complex, we had three auxiliary functions:
- crossDroneGroups
- crossDroneID
- crossColonyID

If we don't allow mating with drone IDs anymore, do we still need them?
